# Sample config for Prometheus.

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_interval: 5s
    static_configs:
      - targets:
        - 172.16.254.254
        - 172.16.254.255
        - 172.16.254.246
        - 172.16.254.247
        - 172.16.254.254
        - 172.16.254.243
        - 172.16.254.244
        - 172.16.254.242
        - 172.16.254.241
        - 172.16.254.19
        - 172.16.254.240
        - 172.16.254.217
        - 172.16.254.218
        - 172.16.254.215
        - 172.16.254.207
        - 172.16.254.214
        - 172.16.254.206
        - 172.16.254.202
        - 172.16.254.208
        - 172.16.254.216
        - 172.16.254.212
        - 172.16.254.210
        - 172.16.254.211
        - 172.16.254.209
        - 172.16.254.205
        - 172.16.254.204
        - 172.16.254.201
        - 172.16.254.213
        - 172.16.254.203
        - 172.16.254.230
        - 172.16.254.221
        - 172.16.254.219
        - 172.16.254.220
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.