apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash-proxy-deployment
  namespace: bissolli
  labels:
    app: unleash-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleash-proxy
  template:
    metadata:
      labels:
        app: unleash-proxy
    spec:
      containers:
      - name: unleash-proxy
        image: unleashorg/unleash-proxy 
        ports:
        - containerPort: 3000
        env:
        - name: UNLEASH_PROXY_CLIENT_KEYS 
          value: "some-secret"
        - name: UNLEASH_URL
          value: "https://app.unleash-hosted.com/orange/api/"
        - name: UNLEASH_API_TOKEN
          value: "*:development.c303632971606e855180a8effc9935c8b1b97284209245315b78b2c8"

---

apiVersion: v1
kind: Service
metadata:
  name: unleash-proxy 
  namespace: bissolli
spec:
  selector:
    app: unleash-proxy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP 

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: bissolli
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: unleash-proxy
spec:
  rules:
  - host: unleash-proxy.dev-ap-south-1.cfood.xyz
    http:
      paths:
        - backend:
            service:
              name: unleash-proxy
              port: 
                number: 3000
          path: /
          pathType: ImplementationSpecific
